services:
  caddy-global:
    image: caddy:latest
    container_name: caddy-global
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - edge-network

networks:
  edge-network:
    external: true

volumes:
  caddy_data:
  caddy_config: