services:

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites/
      - ./certbot-webroot:/var/www/certbot
    ports:
      - 80:80
      - 443:443

  certbot:
    container_name: certbot
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - ./nginx/sites/:/etc/nginx/sites/
      - ./certbot-webroot:/var/www/certbot
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew --webroot -w /var/www/certbot --quiet --deploy-hook \"docker restart reverse-proxy\"; sleep 12h; done'"