services:

  reverse-proxy:
    container_name: reverse-proxy
    image: nginx
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites/
    ports:
      - 80:80
      - 443:443