name: Docker Deployment

on:
  push:
    branches:
      - main

jobs:
  Refresh_reverse_proxy:
    runs-on: ubuntu-latest

    steps:

      - name: Pull git repository into server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd /home/containers/Reverse_proxy_VPS
            git checkout main
            git pull

      - name: Refresh docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          passphrase: ${{ secrets.SERVER_PASSPHRASE }}
          script: |
            cd /home/containers/Reverse_proxy_VPS
            docker compose down --rmi all
            docker compose up -d